---
title: "ggplot basic"
author: "B06208030 何承諭"
date: "2019年7月14日"
output: html_document
---


> 環境建置與觀察資料

```{r warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)

#內建資料iris
head(iris)
```

    1. 花萼長度(Sepal Length)：計算單位是公分。
    2. 花萼寬度(Sepal Width)：計算單位是公分。
    3. 花瓣長度(Petal Length) ：計算單位是公分。
    4. 花瓣寬度(Petal Width)：計算單位是公分。
    5. 類別(Class)：可分為Setosa，Versicolor和Virginica三個品種。



> 基本使用方法

```{r}
# ggplot()裡第一個參數放要畫的資料dataframe
# aes參數裡面裝 "變量" 就像在說一張圖表的x與y軸分別是什麼
# 以+號疊加的方式來決定你的圖要怎麼畫 要畫成甚麼樣子
# 以這裡來舉例 我要畫 根據不同Species 數總數的長條圖
ggplot(iris, aes(x = Species)) +
  geom_bar()

```

```{r}
# 我要畫根據花瓣長度不同的不同種類數量分布圖 (直方圖hist)
ggplot(iris, aes(x = Petal.Length)) +
  geom_histogram(bins = 30) +
  facet_wrap(~Species)
```


```{r}
# 我要畫 Species之間花萼寬度分布的箱形圖
ggplot(iris, aes(x = Species, y = Sepal.Width)) +
  geom_boxplot()
```

```{r}
# 我要畫 花瓣長與寬 的分布圖
ggplot(iris, aes(x = Petal.Length, y = Petal.Width)) +
  geom_point()

```


```{r}
# 再搭配上上周的資料處理套件應用
# 我要畫 花瓣長與寬 & 根據顏色分類Species & 根據花萼面積大小點大小要有所改變 的分布圖
iris_new = iris %>%
  mutate(Sepal.Area = Sepal.Length * Sepal.Width, Petal.Area = Petal.Length * Petal.Width)
head(iris_new)

ggplot(iris_new, aes(x = Petal.Length, y = Petal.Width, color = Species, size = Sepal.Area)) +
  geom_point()
```




